### ISSUE TITLE
ngx.exec ngx.ctx

### ISSUE THREAD

**Issue by yin32167** [openresty/lua-resty-limit-traffic#20]
```
log_by_lua_block {
    local ctx = ngx.ctx
    local lim = ctx.limit_conn
    if lim then
        local latency = tonumber(ngx.var.request_time)
        local key = ctx.limit_conn_key
        assert(key)
        local conn, err = lim:leaving(key, latency)
        if not conn then
           ngx.log(ngx.ERR, err)
           return
        end
    end
}
```

如果我使用了`ngx.exec`进行了转发, 我该如何在`log_by_lua_block`中获取`lim`, 因为ngx.ctx已经销毁了?

**Comment by agentzh** [comment]
@yin32167 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, `ngx.exec` does clear all the context data of the original request handler. It's officially documented:

https://github.com/openresty/lua-nginx-module/#ngxctx

Please read the documentation carefully.

There does exist a workaround to make `ngx.ctx` persistent after the internal redirects proposed in the issue openresty/lua-nginx-module#1057
