### ISSUE TITLE
How can i rate limit by $arg request parameter value?

### ISSUE THREAD

**Issue by rihannarickeminem** [openresty/lua-resty-limit-traffic#22]
Assume i have `userid` field in each request parameter, and i want limit the requests by the parameter value . How to write the config for it?

**Comment by agentzh** [comment]
@rihannarickeminem Just use that URI parameter value as the limiter's key.

**Comment by IzaGz** [comment]
@agentzh thank you ! but it does not work.

>   limit_req_zone $arg_reqbyuser zone=mylimit:10m rate=3r/s;
>     server {
>     listen       8044;
>     ssl                  on;
>     ssl_certificate      /etc/ssl/certs/myssl.crt;
>     ssl_certificate_key  /etc/ssl/private/myssl.key;
>     location /route/{
>       limit_req zone=mylimit burst=2000;
>       proxy_pass https://api.vk.com/;
>     }  }

this way nginx often misses some reqs more then 3r/s. 
But, if i set the `$arg_reqbyuser=some_variableVALUE`
>   limit_req_zone $arg_reqbyuser=some_variableVALUE zone=mylimit:10m rate=3r/
it works, what is wrong?

**Comment by agentzh** [comment]
@IzaGz You know you are commenting on an issue belonging to the lua-resty-limit-traffic library? You're using the standard nginx ngx_limit_req module.

**Comment by findmark** [comment]
> 

In this case, share dict must be definded beforehand, right? Is there any possibility for me to set multiple uris by using only one share dict setting?

**Comment by findmark** [comment]
I used comind to handle my issue, so far it looks good though, not sure it is the best way to do so.

> > 
> 
> In this case, share dict must be definded beforehand, right? Is there any possibility for me to set multiple uris by using only one share dict setting?
