### ISSUE TITLE
Graceful way to "leave" connection while handling error

### ISSUE THREAD

**Issue by A-Scott-Rowe** [openresty/lua-resty-limit-traffic#32]
We are using `incoming` and `leaving` the same was as in the example in the readme. however when the server errors we redirect to an error page, this causes the context to be cleared and we lose the saved connection. 

is there a more graceful way to `leave` the connection in this situation other than opening a new connection in the error handling code?

**Comment by downtown12** [comment]
i meet the same problem, the concurrent level will increase in case of upstream connection errors

**Comment by spacewander** [comment]
What about using https://github.com/tokers/lua-resty-ctxdump to stash ctx before proxy and apply it back in log_by_lua/error_page block?

**Comment by downtown12** [comment]
@spacewander Thanks. I have tested. It seems lua-resty-ctxdump module can solve the internal requests losing main request's ctx problem.

**Comment by spacewander** [comment]
The `ctx` is cleared by Nginx when it does internal redirect. As the workaround works I decide to close this issue. Feel free to reopen it if you still have problem.
