### ISSUE TITLE
prefer HTTP_TOO_MANY_REQUESTS over HTTP_SERVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by nicoster** [openresty/lua-resty-limit-traffic#43]
In the sample code it return ngx.HTTP_SERVICE_UNAVAILABLE when rejecting a request. 
Is ngx.HTTP_TOO_MANY_REQUESTS more suitable here?

**Comment by agentzh** [comment]
This is just to be consistent with the standard nginx modules `ngx_http_limit_req` and `ngx_http_limit_conn`. You can of course use any other status codes for your needs in your own Lua code anyway.
