### ISSUE TITLE
limit connection 's question

### ISSUE THREAD

**Issue by cellcb** [openresty/lua-resty-limit-traffic#9]
hi 
i have a question about " CONN.LUA"
ngx.shared.DICT.incr is atomic operation?

How to ensure  “conn, err = dict:incr(key, -1)” is right 

thank you

**Comment by doujiang24** [comment]
Yes, it's atomic operation :)

**Comment by cellcb** [comment]
I USE JMETER testing pressure   
DICT:INCR  cant ensure is right

**Comment by agentzh** [comment]
@cellcb All the shdict methods are atomic, regardless the number of your nginx worker processes or concurrency level. I'm having problems understanding your English. Sorry. I'm closing this.
